---
- name: Setup the homeserver
  hosts: all
  become: true

  tasks:
    - name: Update server and install essential packages
      ansible.builtin.include_tasks: tasks/essential.yml

    - name: Install docker
      ansible.builtin.include_tasks: tasks/docker.yml

    - name: Deploy docker apps
      ansible.builtin.include_tasks: "tasks/{{ item }}.yml"
      loop:
        - authelia
        - traefik
        - code_server
        - dashdot
        - duplicati
        - filebrowser
        - guacamole
        - heimdall
        - homarr
        - jellyfin
        - jellyseerr
        - monitoring
        - portainer
        - prowlarr
        - qbittorrent
        - radarr
        - sonarr
        - syncthing
        - unmanic
        - uptime_kuma
        - vaultwarden
        - watchtower
        - wireguard

    - name: Modify ownership of data and docker_apps directories
      ansible.builtin.include_tasks: tasks/add_ownership.yml

    - name: Reboot the server
      ansible.builtin.reboot:
        msg: "Rebooting server to finish setup"
